@extends('shopify-app::layouts.default')

@section('content')

<div class="pt-4 px-4 pb-20">
    <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-800">Terms of service</h2>
    A. Introduction<br/>
PLEASE READ THESE TERMS OF SERVICE CAREFULLY. THESE TERMS OF SERVICE INCLUDE THE REQUIRE THAT USE OF THE SERVICE BE CONDITIONED ON ALL DISPUTES BETWEEN US BEING RESOLVED BY FINAL AND BINDING ARBITRATION ON AN INDIVIDUAL AND NOT A CLASSWIDE OR CONSOLIDATED BASIS. THE MANDATORY ARBITRATION PROVISION APPLIES TO USA RESIDENTS AND RESIDENTS THROUGHOUT THE WORLD UNLESS YOU ARE A CONSUMER IN THE EUROPEAN UNION. PLEASE READ THESE TERMS OF SERVICE CAREFULLY. BY REGISTERING FOR, ACCESSING, BROWSING, DOWNLOADING FROM OR USING THE Cander SERVICE, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS OF SERVICE. IF AT ANY TIME YOU DO NOT AGREE TO THESE TERMS OF SERVICE, PLEASE IMMEDIATELY TERMINATE YOUR USE OF THE Cander SERVICE OR, IF YOU ARE A CONSUMER RESIDENT IN THE EUROPEAN UNION, CONTACT US AT LEGAL@Cander.COM TO DISCUSS ANY CONCERNS YOU MAY HAVE REGARDING THESE TERMS OF SERVICE. IF YOU ARE USING OR OPENING AN ACCOUNT WITH Cander ON BEHALF OF A COMPANY, ENTITY, OR ORGANIZATION (COLLECTIVELY, A "SUBSCRIBING ORGANIZATION") THEN YOU REPRESENT AND WARRANT THAT YOU: (I) ARE AN AUTHORIZED REPRESENTATIVE OF THAT SUBSCRIBING ORGANIZATION WITH THE AUTHORITY TO BIND SUCH ORGANIZATION TO THESE TERMS OF SERVICE; (II) HAVE READ THE FOREGOING TERMS; (III) UNDERSTAND THESE TERMS OF SERVICE, AND (IV) AGREE TO THESE TERMS OF SERVICE ON BEHALF OF SUCH SUBSCRIBING ORGANIZATION.<br/>
<br/>1. Your Agreement to these Terms of Service.<br/>
Thank you for using the streaming platform operated by Cander, LLC ("Cander") consisting of the web site available at the URL http://www.Cander.com and all related services, software applications and networks that allow for the authorized streaming and distribution video content over the internet and other data networks (the "Cander Service"). The Cander Service also includes any other sites or services that link to these terms of service (the "Terms of Service"). Other services offered by Cander may be subject to separate terms.<br/>
The following Terms of Service for the Cander Service is a legal contract between you, an individual user of at least 13 years of age or a single entity ("you"), and Cander ("us") regarding your use of the Cander Service. If you are a minor, or a parent/guardian of a minor seeking to use the Cander Service, please see section 2 below about minors using the Cander Service.<br/>
Cander may offer certain additional services for which you can agree to pay fees to Cander. The applicable terms will be made available on the applicable Cander web page and will supplement these Terms of Service. If you register and/or use any such paid fee services, you will be asked to agree to and comply with the Cander Terms of Sale. You will treat the Cander Terms of Sale as though it is part of these Terms of Service (which it is).<br/>
<br/>
2. Use of Cander by Minors and Blocked Persons.<br/>
You must be 13 years of age or older to use the Cander Service. If you are between the ages of 13 and 18 (or between 13 and the age of legal majority in your country of residence), you may only use the Cander Service under the supervision of a parent or legal guardian who agrees to be bound by these Terms of Service. BY DOWNLOADING, INSTALLING OR OTHERWISE USING THE Cander SERVICE, YOU REPRESENT THAT YOU ARE AT LEAST 13 YEARS OF AGE, ARE USING THE SERVICE UNDER THE SUPERVISION OF A PARENT OR LEGAL GUARDIAN WHO AGREES TO BE BOUND BY THESE TERMS OF SERVICE .<br/>
The Cander Service is also not available to any users, no matter the age or if the user is an entity, if your account has been previously deactivated by us unless we (in our sole discretion) decide to reactivate your existing account or grant you the opportunity to create a new account (see section 16 below for more about suspension or removal).<br/>
<br/>
3. Privacy Policy.<br/>
Your privacy is important to Cander. Please see our Privacy Policy for information relating to how we collect, use, and disclose your personal information.<br/>
<br/>
4. License<br/>
The Cander Service is owned and operated by Cander. Unless otherwise indicated, all Content and other materials on the Cander Services, including, without limitation, Cander's logos, the visual interfaces, graphics, design, compilation, information, software, computer code (including source code or object code), services, text, pictures, information, data, sound files, other files and the selection and arrangement there of (collectively, the "Materials") are protected by United States copyright, trade dress, patent, and trademark laws, international conventions, and all other relevant intellectual property and proprietary rights, and applicable laws (including in your country of residence). All Materials contained on the Cander Service are the proprietary property of Cander or its subsidiaries or affiliated companies and/or third- party licensors. All trademarks, service marks, and trade names are proprietary to Cander or its affiliates and/or third-party licensors. Cander expressly reserves all rights not expressly granted in these Terms of Service.<br/>
Unless otherwise expressly stated in writing by Cander, you are only granted a limited, non-sublicensable license to access and use the Cander Service for your personal or internal business use only (the "Your Limited Right"). In other words, this right which we grant to you is a limited to you and you cannot grant this right to any person or entity without our approval.<br/>
Your Limited Right is subject to these Terms of Service. Your Limited Right does not include any of the following: (a) any resale or commercial use of the Cander Service or the Materials; (b) the distribution, public performance or public display of any Materials (except for Broadcaster Content by the Broadcaster posting the Broadcaster Content - this is all explained further below); (c) modifying or otherwise making any derivative uses of the Cander Service or the Materials, or any portion of them; (d) use of any data mining, robots or similar data gathering or extraction methods; (e) downloading (except page caching) of any portion of the Cander Service, the Materials or any information contained in them, except as expressly permitted on the Cander Service; or (f) any use of the Cander Service or the Materials except for their intended purposes. Any use of the Cander Service or the Materials except as specifically authorized in these Terms of Service, without the prior written permission of Cander, is strictly prohibited and your failure to comply with them may have legal consequences which may include violating applicable laws, including copyright and trademark laws and applicable communications regulations and statutes. Unless explicitly stated in these Terms of Service, nothing in them shall be interpreted as conferring any license to intellectual property rights, whether by estoppel, implication or other legal principles. Your Limited Right can be terminated by us at any time in accordance with Section 16.<br/>
<br/>
5. Individual Features and Services.<br/>
When using the Cander Service, you will be subject to any additional posted guidelines or rules applicable to specific contests, promotions, services and features which may be posted online and/or otherwise notified to you from time to time (the "Guidelines"). All these Guidelines are (and must treat them as if they are) belong to these Terms of Service. In the event of a conflict between any Guidelines or these Terms of Service, we ask you to use common sense and that you contact our [CUSTOMER SUPPORT] but you can and should assume that the terms of these Terms of Service shall prevail.<br/>
<br/>
6. Modification of these Terms of Service.<br/>
Cander reserves the right, at our discretion, to change, modify, add, or remove portions of these Terms of Service at any time (for example to reflect updates to the Cander Service or to reflect changes in the law). If Cander makes material changes to these Terms of Service, we will provide you with reasonable prior written notice of these changes, such as by sending an email, posting a notice on the Cander Service or updating the "Last Updated" date above. Please check these Terms of Service and any Guidelines periodically for those changes. Your continued use of the Cander Service after the posting of changes constitutes your binding acceptance of such changes.<br/>
<br/>
7. Digital Millennium Copyright Act.<br/>
Please note that our Service, by its nature, incorporates content that is user generated. We respect content owners and want to promote their lawful use of content as well as their right to remove certain content from our Service if it is being used without permission. Content may include, words, game designer, game publisher, music, and other Content (as defined below) owner rights, it is Cander's policy to respond to notices of alleged infringement that comply with the Digital Millennium Copyright Act (the "DMCA"). If you believe that anything in the Cander Services infringes upon any copyright that you own or control, you may file a notification of such infringement with our Designated Agent as set forth below.<br/>
Name of Designated Agent: Ruvin Spivak, General Counsel<br/>
Address of Designated Agent: [ADDRESS]; Attention: Copyright Agent<br/>
Email Address of Designated Agent: dmca@Cander.com<br/>
Please see 17 U.S.C. Â§512Â©(3) for the requirements of a proper notification. To be effective, the notification to us must be in writing and must comply with the following minimum requirements:<br/>
Written notices must be sent either: (1) electronically sent to the email address listed in this section above with subject line "DMCA Takedown Request". Requests sent to such email address for any purpose other than regarding violations of intellectual property rights may not be answered; or (2) via courier (with a confirmed receipt requested) to the mailing address listed in this section above.<br/>
Each written notification must contain the following information: an electronic or physical signature of the person authorized to act on behalf of the owner of the exclusive copyright interest;<br/>
a description of the copyrighted work that you claim has been infringed;<br/>
a description of where the material that you claim is infringing is located on the Swagbucks.com Sites that is reasonably sufficient to enable us to identify and locate the material (for example, a list of URLs); o your physical mailing address, telephone number and email address;<br/>
a statement by you affirming that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; and<br/>
a statement by you that the information provided in your notice is accurate and, under penalty of perjury, that you are the owner of an exclusive right in the material or that you are authorized to act on behalf of the copyright owner.<br/>
We will process each written notice of alleged infringement that we receive and will take appropriate action in accordance with applicable intellectual property laws. You should note that if you knowingly misrepresent in your notification that the material or activity is infringing, you will be liable for any damages, including costs and attorneys' fees, incurred by us or the alleged infringer as the result of our relying upon such misrepresentation in removing or disabling access to the material or activity claimed to be infringing.<br/>
<br/>
8. Other Intellectual Property Rights Infringement Systems in the EU and Rest of the World.<br/>
If you believe that your copyright or other intellectual property rights have been infringed and they are not subject to US law and jurisdiction (for example, if you consider the infringement is subject to the Ecommerce Directive of the European Union), then we invite you to contact us using the procedure set out at section 7) for the US Digital Millennium Copyright Act to the extent relevant. You can contact dmca@Cander.com if you wish to discuss this further with us.<br/>
<br/>
9. Repeat Infringer Policy.<br/>
In accordance with the DMCA and other applicable laws around the world, Cander has adopted a policy that it may, in its sole discretion, promptly terminate without notice any user's access to the Cander Service if that user is determined by Cander to be a "repeat infringer." A repeat infringer includes, without limitation a user who has been notified by Cander of infringing activity violations more than twice and/or who has had their Broadcaster Content or any other user submitted content removed from the Cander Service more than twice. Cander may also at our sole discretion limit access to the Cander Service and/or terminate the accounts of any users who infringe any intellectual property rights of others, whether or not there is any repeat infringement.<br/>
In addition, Cander accommodates and does not interfere with standard technical measures used by intellectual property rights owners to protect their materials.<br/>
<br/>
10. Trademarks.<br/>
Cander, the Cander logos and any other product or service name or slogan contained in the Cander Service are trademarks of Cander or our suppliers or licensors and may not be copied, imitated or used, in whole or in part, without the prior written permission of Cander or the applicable trademark holder. Any authorized use of these trademarks must be in accordance with any guidelines that Cander may provide you from time to time.<br/>
You may not use any metatags or any other hidden text utilizing "Cander" or any other name, trademark or product or service name of Cander without our prior written permission. In addition, the look and feel of the Cander Service, including all page headers, custom graphics, button icons and scripts, is the service mark, trademark and/or trade dress of Cander and may not be copied, imitated or used, in whole or in part, without our prior written permission. All other trademarks, registered trademarks, product names and company names or logos mentioned in the Cander Service are the property of their respective owners. Reference to any products, services, processes or other information, by trade name, trademark, manufacturer, supplier or otherwise does not constitute or imply endorsement, sponsorship or recommendation thereof by us or any other affiliation.<br/>
<br/>
11. Broadcasters.<br/>
Cander allows certain users ("Broadcaster") to distribute streaming live and prerecorded Content.<br/>
11.1 License from Cander.<br/>
If you sign up for an account as a Broadcaster, subject to your compliance with these Terms of Service, Cander hereby grants to you a personal, limited, nonexclusive, nontransferable, freely revocable license to use the Cander Service for the uploading and distributing of authorized digital Content, including videos ("Broadcaster Content").<br/>
11.2 License to Cander<br/>
Unless otherwise agreed to in a written agreement between you and Cander that was signed by an authorized representative of Cander:<br/>
1. By distributing or disseminating Broadcaster Content through the Cander Service, you hereby grant to Cander a worldwide, non-exclusive, royalty-free, perpetual, transferable and fully sublicensable right to use, host, convert for streaming, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform, display and otherwise exploit your Broadcaster Content, in any form, format, media or media channels now known or later developed or discovered. You grant Cander and our sub-licensees the right to use the name that you submit in connection with that content, if we or they choose.<br/>
2. Except for Broadcaster Content already downloaded by users, the foregoing license granted by you terminates regarding a specific piece of Broadcaster Content once you remove or delete that Broadcaster Content from the Cander Service.<br/>
11.3 Broadcaster Content Representations and Warranties.<br/>
You are solely responsible for your Broadcaster Content and the consequences of posting or publishing it. By uploading and publishing your Broadcaster Content, you represent, and warrant that: (1) you are the creator and owner of the Broadcaster Content or otherwise have sufficient rights and authority to grant the rights granted herein; (2) your Broadcaster Content does not and will not (a) infringe, violate, or misappropriate any third-party right, including any copyright, trademark, patent, trade secret, moral right, privacy right, right of publicity, or any other intellectual property or proprietary right or (b) slander, defame, or libel any other person; (3) your Broadcaster Content does not contain any viruses, adware, spyware, worms, or other harmful or malicious code or (4) unless you have received prior written authorization, your Broadcaster Content specifically does not contain any confidential information of Cander or third parties. Cander reserves all rights and remedies against any Broadcasters who breach these representations and warranties.<br/>
11.4 Content is Uploaded at Your Own Risk.<br/>
Cander uses reasonable security measures in order to attempt to protect Broadcaster Content. However Cander cannot guarantee that there will be no unauthorized copying or distribution of Broadcaster Content nor will Cander be liable for any copying or usage of the Broadcaster Content not authorized by Cander. You hereby release and forever waive any claims you may have against Cander for any such unauthorized copying or usage of the Broadcaster Content, under any theory. THE SECURITY MEASURES TO PROTECT BROADCASTER CONTENT USED BY Cander HEREIN ARE PROVIDED AND USED "AS IS" AND WITH NO WARRANTIES OR ASSURANCES THAT SUCH SECURITY MEASURES WILL WITHSTAND ATTEMPTS TO EVADE SECURITY MECHANISMS OR THAT THERE WILL BE NO CRACKS, DISABLEMENTS OR OTHER CIRCUMVENTION OF SUCH SECURITY MEASURES.<br/>
11.5 Prevention of Unauthorized Use of Broadcaster account.<br/>
Unless expressly permitted in writing by Cander, you may not sell, rent, lease, share or provide access to your Broadcaster account to any third party, including, without limitation, charging any remuneration (e.g. money) to any third party for access to administrative rights on your Broadcaster account. Cander reserves all available legal rights and remedies to prevent unauthorized use of the Cander Service, including, but not limited to, technological barriers, IP mapping, and in serious cases directly contacting your Internet Service Provider (ISP) regarding such unauthorized use.<br/>
11.6 Promotions<br/>
Broadcasters may promote, administer or conduct a promotion on, through or utilizing Cander (a "Promotion"). If you are a Broadcaster and you choose to promote, administer or conduct a Promotion, you must follow the following rules:<br/>
11.6.1 You may carry out Promotions to the extent permitted by applicable local law and you are solely responsible for ensuring that you and any Promotions comply with any and all applicable local law obligations and restrictions.<br/>
11.6.2 You, at your expense, will be solely responsible for all aspects of your Promotion, including, without limitation, the execution, administration, and operation of the Promotion; drafting and posting any official rules; selecting winners; issuing prizes; and obtaining all necessary third-party permissions and approvals, including, without limitation, filing any and all necessary registrations and bonds. Cander has the right to remove your Promotion from the Cander Service for any reason.<br/>
11.6.3 Cander is not responsible for and does not endorse or support any such Promotions. You may not indicate that Cander is a sponsor or cosponsor of the Promotion without our express prior written approval in each instance.<br/>
11.6.4 ALL Broadcasters should display or read out the following when a Promotion is on their channel: "This is a promotion from [channel name] . Cander does not sponsor or endorse broadcaster promotions and is not responsible for them".<br/>
11.7 Endorsements/Testimonials<br/>
You agree that your Broadcaster Content will comply with the FTC's Guidelines Concerning the Use of Testimonials and Endorsements in Advertising ("Guidelines"). For example, if you have been paid or provided with free products in exchange for discussing or promoting a product or service through the Cander Service, or if you are an employee of a company and you decide to discuss or promote that company's products or services through the Cander Service, you agree to comply with the Guidelines' requirements for disclosing such relationships. You, and not Cander, are solely responsible for any endorsements or testimonials you make regarding any product or service through the Cander Service.<br/>
<br/>
12. Third Party Content.<br/>
In addition to the Broadcaster Content, Cander may provide other third party content on the Cander Services and may provide links to Web pages and content of third parties (collectively the "Third Party Content") as a service to those interested in this information. Cander does not control, endorse or adopt any Third Party Content and makes no representation or warranties of any kind regarding the Third Party Content, including without limitation regarding its accuracy or completeness. Please be aware that we do not create Third Party Content, nor we do not update or monitor it, therefore we are not responsible for any Third Party Content on the Cander Service. Users use such Third Party Content at their own risk.<br/>
The Cander Service may include links or references to other web sites or services solely as a convenience to Users ("Reference Sites"). Cander does not endorse any such Reference Sites or the information, materials, products, or services contained on or accessible through Reference Sites. In addition, your correspondence or business dealings with, or participation in promotions of, advertisers found on or through the Cander Service are solely between you and such advertiser. Access and use of Reference Sites, including the information, materials, products, and services on or available through Reference Sites is solely at your own risk.<br/>
<br/>
13. Prohibited Conduct.<br/>
The Cander Services may include interactive areas or services ("Interactive Areas"), such as 2-way video communication, chat boxes or web forums, in which you or other users may create, post or store content, messages, materials, data, information, text, music, sound, photos, video, graphics, applications, code or other items or materials on the Cander Services ("User Content" and collectively with Broadcaster Content, "Content"). You are solely responsible for your use of such Interactive Areas and use them at your own risk. BY USING THE Cander SERVICE, INCLUDING THE INTERACTIVE AREAS, YOU AGREE NOT TO violate any law, contract, intellectual property or other Third Party right or commit a tort, and that you are solely responsible for your conduct while on the Cander Service.<br/>
You agree that you will comply with these Terms of Service and all rules of conduct found through the Cander Service and will not:<br/>
use the Cander Service for any purposes except to disseminate or receive original or appropriately licensed content and/or to access the Cander Service;<br/>
rent, lease, loan, sell, resell, sublicense, distribute or otherwise transfer the licenses granted in these Terms of Service or any Materials (as defined in section 4);<br/>
post, upload, or distribute any defamatory, libellous, or inaccurate Content;<br/>
impersonate any person or entity, falsely claim an affiliation with any person or entity, or access the Cander Service accounts of others without permission, forge another persons' digital signature, misrepresent the source, identity, or content of information transmitted via the Cander Service, or perform any other similar fraudulent activity;<br/>
delete the copyright or other proprietary rights notices on the Cander Service or Content;<br/>
make unsolicited offers, advertisements, proposals, or send junk mail or spam to other Users of the Cander Service, including, without limitation, unsolicited advertising, promotional materials, or other solicitation material, bulk mailing of commercial advertising, chain mail, informational announcements, charity requests, petitions for signatures, or any of the preceding things related to promotional giveaways (such as raffles and contests), and other similar activities;<br/>
harvest or collect the email addresses or other contact information of other users from the Cander Service for the purpose of sending spam or other commercial messages;<br/>
use the Cander Service for any illegal purpose, or in violation of any local, state, national, or international law, including, without limitation, laws governing intellectual property and other proprietary rights, and data protection and privacy;<br/>
defame, harass, abuse, threaten or defraud Users of the Cander Service, or collect, or attempt to collect, personal information about Users or third parties without their consent;<br/>
remove, circumvent, disable, damage or otherwise interfere with security related features of the Cander Service or Content, features that prevent or restrict use or copying of any content accessible through the Cander Service, or features that enforce limitations on the use of the Cander Service or Content;<br/>
reverse engineer, decompile, disassemble or otherwise attempt to discover the source code of the Cander Service or any part thereof, except and only to the extent that this activity is expressly permitted by the law of your country of residence;<br/>
modify, adapt, translate or create derivative works based upon the Cander Service or any part thereof, except and only to the extent that such activity is expressly permitted by applicable law notwithstanding this limitation;<br/>
intentionally interfere with or damage operation of the Cander Service or any user's enjoyment of them, by any means, including uploading or otherwise disseminating viruses, adware, spyware, worms, or other malicious code;<br/>
relay email from a third party's mail servers without the permission of that third party;<br/>
use any robot, spider, scraper, crawler or other automated means to access the Cander Service for any purpose or bypass any measures Cander may use to prevent or restrict access to the Cander Service;<br/>
manipulate identifiers in order to disguise the origin of any Content transmitted through the Cander Service;<br/>
interfere with or disrupt the Cander Service or servers or networks connected to the Cander Service, or disobey any requirements, procedures, policies or regulations of networks connected to the Cander Service; use the Cander Service in any manner that could interfere with, disrupt, negatively affect or inhibit other users from fully enjoying the Cander Service, or that could damage, disable, overburden or impair the functioning of the Cander Service in any manner;<br/>
use or attempt to use another user's account without authorization from that user and Cander;<br/>
attempt to circumvent any content filtering techniques we employ, or attempt to access any service or area of the Cander Service that you are not authorized to access; or<br/>
attempt to indicate in any manner that you have a relationship with us or that we have endorsed you or any products or services for any purpose.<br/>
Further, BY USING THE Cander SERVICE, INCLUDING THE INTERACTIVE AREAS YOU AGREE NOT TO post, upload to, transmit, distribute, store, create or otherwise publish through the Cander Service any of the following:<br/>
Content that would constitute, encourage or provide instructions for a criminal offense, violate the rights of any party, or that would otherwise create liability or violate any local, state, national or international law or regulation;<br/>
Content that may infringe any patent, trademark, trade secret, copyright or other intellectual or proprietary right of any party. By posting any Content, you represent and warrant that you have the lawful right to distribute and reproduce such Content;<br/>
Content that is unlawful, libelous, defamatory, obscene, pornographic, indecent, lewd, suggestive, harassing, threatening, invasive of privacy or publicity rights, abusive, inflammatory, fraudulent or otherwise objectionable;<br/>
Content that impersonates any person or entity or otherwise misrepresents your affiliation with a person or entity;<br/>
private information of any third party, including, without limitation, addresses, phone numbers, email addresses, Social Security numbers and credit card numbers;<br/>
viruses, corrupted data or other harmful, disruptive or destructive files; and<br/>
Content that, in the judgment of Cander, is objectionable or which restricts or inhibits any other person from using or enjoying the Interactive Areas or the Cander Service, or which may expose Cander or our users to any harm or liability.<br/>
Cander takes no responsibility and assumes no liability for any Content posted, stored or uploaded by you or any third party, or for any loss or damage thereto, nor is Cander liable for any mistakes, defamation, slander, libel, omissions, falsehoods, obscenity, pornography or profanity you may encounter. YOUR USE OF THE Cander SERVICE IS AT YOUR OWN RISK. Enforcement of the user content or conduct rules set forth in these Terms of Service is solely at Cander's discretion, and failure to enforce such rules in some instances does not constitute a waiver of our right to enforce such rules in other instances. In addition, these rules do not create any private right of action on the part of any third party or any reasonable expectation that the Cander Service will not contain any content that is prohibited by such rules. As a provider of interactive services, Cander is not liable for any statements, representations or Content provided by our users in any public forum, personal home page or other Interactive Area. Cander does not endorse any Content or any opinion, recommendation or advice expressed therein, and Cander expressly disclaims any and all liability in connection with Content. Although Cander has no obligation to screen, edit or monitor any of the Content posted in any Interactive Area, Cander reserves the right, and has absolute discretion, to remove, screen or edit any Content posted or stored on the Cander Service at any time and for any reason without notice, and you are solely responsible for creating backup copies of and replacing any Content you post or store on the Cander Service at your sole cost and expense. Any use of the Interactive Areas or other portions of the Cander Service in violation of the foregoing violates these Terms and may result in, among other things, termination or suspension of your rights to use the Interactive Areas and/or the Cander Service.<br/>
<br/>
14. Rights in User Content.<br/>
If you submit or post User Content to the Cander Service you grant Cander a worldwide, non-exclusive, royalty free, perpetual, irrevocable and fully sub-licensable right to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform and display such User Content in any form, format, media or media channels now known or hereafter developed or discovered. You grant Cander and our sub-licensees the right to use the names and likenesses that you submit in connection with such content, if we or they choose.<br/>
By submitting or posting User Content to the Cander Service, you agree that: (a) such User Content is non-confidential; (b) you own and control all of the rights to the User Content that you post or you otherwise have all necessary rights to post such User Content to the Cander Service; (c) the User Content is accurate and not misleading or harmful in any manner; and (d) the User Content, and your use and posting of that User Content in connection with the Cander Service, does not and will not violate these Terms of Service or any applicable law, rule or regulation in your country or elsewhere.<br/>
<br/>
15. Account<br/>
15.1. Account and Password.<br/>
You may wish to open a Cander account with us for a number of reasons, including a more personalized Cander experience or to upload and/or download or purchase content or any products, services, or information from Cander. In order to open an account, you will asked to provide us with certain information like an account name and password (all of which will be protected by our Privacy Policy).<br/>
Once you have a Cander account you can purchase products and services (including subscriptions) via Cander. The Cander Terms of Sale explain how this works  please read carefully this important document, which is incorporated by reference into these Terms of Service (this means they legally form part of this document).<br/>
While Cander uses reasonable security precautions, you are solely responsible for maintaining the confidentiality of your account and password, for restricting access to your computer and for all activities that occur under your account or password. Please make sure you provide to Cander on registration and at all other times information which will be true, accurate, current, complete and kept up to date to the best of your ability.<br/>
If you have reason to believe that your account is no longer secure (e.g., in the event of a loss, theft or unauthorized disclosure or use of your account ID, password, or any credit, debit or charge card number, if applicable), then you must immediately notify Cander at legal@Cander.com.<br/>
15.2. Third Party Accounts.<br/>
Cander may permit you to register for and log onto the Cander Service via certain third-party social networks, such as by using Facebook Connect. If you log in via such social networks, the profile information connected to the account you use to log into the Cander Service, including your name and email address, may be used by Cander in order to provide and support your account and to communicate with you. You also acknowledge and agree that Cander may publish information regarding your use of the Cander Service to and in connection with any such third party social network with which you use the Cander Service (unless you tell us otherwise).<br/>
<br/>
16. Termination.<br/>
Cander reserves the right, without notice and in our sole discretion, to terminate your license to use the Cander Service (including to post Broadcaster Content), and to block or prevent your future access to and use of the Cander Service. This includes Cander having the ability to terminate or to suspend your access to any purchased products or services. Your only remedy with respect to any dissatisfaction with (i) the Cander Service, (ii) any term of these Terms of Service, (iii) any policy or practice of Cander in operating the Cander Service, or (iv) any content or information transmitted through the Cander Service, is to terminate your account and discontinuing use of any and all parts of the Cander Service. In serious cases of breach of these Terms of Service (for example, infringement of Cander's intellectual property rights or actions causing it financial loss), Cander may consider it appropriate to take legal action against you (though we will try to resolve matters amicably with you if possible).<br/>
<br/>
17. Indemnification.<br/>
The following section only applies to you if you are resident in the USA or elsewhere in the world (but does not apply if you are a consumer resident in the European Union):<br/>
You agree to indemnify, defend, and hold harmless Cander, its affiliated companies, contractors, employees, agents and its Third Party suppliers, licensors, and partners from any claims, losses, damages, liabilities, including legal fees and expenses, arising out of your use or misuse of the Cander Service, any Content you post, store or otherwise transmit in or through the Cander Service, your violation of the rights of any third party, any violation by you of these Terms of Service, or any breach of the representations, warranties, and covenants made by you herein. Cander reserves the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify Cander, and you agree to cooperate with Cander's defense of these claims. Cander will use reasonable efforts to notify you of any such claim, action, or proceeding upon becoming aware of it. If you are a Broadcaster, the forgoing indemnity includes, without limitation, any claims, losses, damages, liabilities, including legal fees and expenses, arising out of your Promotions or Broadcaster Content.<br/>
<br/>
18. Disclaimers; No Warranties.<br/>
The following section only applies to you if you are resident in the USA or elsewhere in the world (but does not apply if you are a consumer resident in the European Union): TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW: (A) THE Cander SERVICE AND THE CONTENT AND MATERIALS CONTAINED THEREIN ARE PROVIDED ON AN "AS IS" BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, EXCEPT AS EXPRESSLY PROVIDED TO THE CONTRARY IN A WRITING BY Cander; (B) Cander, AND ITS AFFILIATES, PARTNERS, AND SUPPLIERS ("Cander PARTIES") DISCLAIM ALL OTHER WARRANTIES, STATUTORY, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NONINFRINGEMENT AS TO THE Cander SERVICE, INCLUDING ANY INFORMATION, CONTENT OR MATERIALS CONTAINED THEREIN; (C) Cander DOES NOT REPRESENT OR WARRANT THAT CONTENT OR MATERIALS ON THE Cander SERVICE ARE ACCURATE, COMPLETE, RELIABLE, CURRENT OR ERRORFREE; (D) Cander IS NOT RESPONSIBLE FOR TYPOGRAPHICAL ERRORS OR OMISSIONS RELATING TO TEXT OR PHOTOGRAPHY; AND (E) WHILE Cander ATTEMPTS TO MAKE YOUR ACCESS AND USE OF THE Cander SERVICE SAFE, Cander CANNOT AND DOES NOT REPRESENT OR WARRANT THAT THE Cander SERVICE OR OUR SERVER(S) ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS, AND THEREFORE, YOU SHOULD USE INDUSTRYRECOGNIZED SOFTWARE TO DETECT AND DISINFECT VIRUSES FROM ANY DOWNLOAD. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM Cander OR THROUGH THE Cander SERVICE WILL CREATE ANY WARRANTY NOT EXPRESSLY STATED HEREIN. YOU EXPRESSLY ACKNOWLEDGE THAT AS USED IN THIS SECTION 17, THE TERM "Cander" INCLUDES Cander'S OFFICERS, DIRECTORS, EMPLOYEES, SHAREHOLDERS, AGENTS, LICENSORS AND SUBCONTRACTORS.<br/>
<br/>
19. Limitation of Liability and Damages.<br/>
Users in the USA and rest of the world (non-EU):<br/>
The following section only applies to you if you are resident in the USA or elsewhere in the world (but does not apply if you are a consumer resident in the European Union):<br/>
19.1 Limitation of Liability.<br/>
TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW: (A) IN NO EVENT SHALL Cander OR THE Cander PARTIES BE LIABLE FOR ANY DIRECT, SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY OTHER DAMAGES OF ANY KIND, INCLUDING BUT NOT LIMITED TO LOSS OF USE, LOSS OF PROFITS OR LOSS OF DATA, WHETHER IN AN ACTION IN CONTRACT, TORT (INCLUDING BUT NOT LIMITED TO NEGLIGENCE) OR OTHERWISE, ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE USE OF OR INABILITY TO USE THE Cander SERVICE, THE CONTENT OR THE MATERIALS, INCLUDING WITHOUT LIMITATION ANY DAMAGES CAUSED BY OR RESULTING FROM RELIANCE BY USER ON ANY INFORMATION OBTAINED FROM Cander, OR THAT RESULT FROM MISTAKES, OMISSIONS, INTERRUPTIONS, DELETION OF FILES OR EMAIL, ERRORS, DEFECTS, VIRUSES, DELAYS IN OPERATION OR TRANSMISSION OR ANY FAILURE OF PERFORMANCE, WHETHER OR NOT RESULTING FROM ACTS OF GOD, COMMUNICATIONS FAILURE, THEFT, DESTRUCTION OR UNAUTHORIZED ACCESS TO Cander'S RECORDS, PROGRAMS OR SERVICES; AND (B) IN NO EVENT SHALL THE AGGREGATE LIABILITY OF Cander, WHETHER IN CONTRACT, WARRANTY, TORT (INCLUDING NEGLIGENCE, WHETHER ACTIVE, PASSIVE OR IMPUTED), PRODUCT LIABILITY, STRICT LIABILITY OR OTHER THEORY, ARISING OUT OF OR RELATING TO THE USE OF OR INABILITY TO USE THE Cander SERVICE EXCEED THE AMOUNT PAID BY YOU, IF ANY, FOR ACCESSING THE Cander SERVICE DURING THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE DATE OF THE CLAIM OR ONE HUNDRED DOLLARS, WHICHEVER IS GREATER.<br/>
19.2 Reference Sites.<br/>
THESE LIMITATIONS OF LIABILITY ALSO APPLY WITH RESPECT TO DAMAGES INCURRED BY YOU BY REASON OF ANY PRODUCTS OR SERVICES SOLD OR PROVIDED ON ANY REFERENCE SITES OR OTHERWISE BY THIRD PARTIES OTHER THAN Cander AND RECEIVED THROUGH OR ADVERTISED ON THE Cander SERVICE OR RECEIVED THROUGH ANY REFERENCE SITES.<br/>
19.3 Basis of the Bargain.<br/>
YOU ACKNOWLEDGE AND AGREE THAT Cander HAS OFFERED THE Cander SERVICES, BROADCASTER CONTENT, MATERIALS AND OTHER CONTENT AND INFORMATION, SET ITS PRICES, AND ENTERED INTO THESE TERMS OF SERVICE IN RELIANCE UPON THE WARRANTY DISCLAIMERS AND THE LIMITATIONS OF LIABILITY SET FORTH HEREIN, THAT THE WARRANTY DISCLAIMERS AND THE LIMITATIONS OF LIABILITY SET FORTH HEREIN REFLECT A REASONABLE AND FAIR ALLOCATION OF RISK BETWEEN YOU AND Cander, AND THAT THE WARRANTY DISCLAIMERS AND THE LIMITATIONS OF LIABILITY SET FORTH HEREIN FORM AN ESSENTIAL BASIS OF THE BARGAIN BETWEEN YOU AND Cander. Cander WOULD NOT BE ABLE TO PROVIDE THE Cander SERVICE TO YOU ON AN ECONOMICALLY REASONABLE BASIS WITHOUT THESE LIMITATIONS.<br/>
19.4 Users in the European Union.<br/>
The following section only applies to you if you are a consumer resident in the European Union: Neither Cander and its affiliates and partners in all cases, nor you (if you are an individual customer), will be responsible for: (i) losses that were not caused by any breach on their or your part; (ii) any indirect or consequential losses (including loss of profits, revenue, contracts, anticipated savings, data, goodwill or wasted expenditure); or (iii) any indirect or consequential losses that were not foreseeable by both you and us when the Terms of Service were agreed or updated as applicable. If you are a Subscribing Organisation (as defined in section 1 of these Terms of Service) then you are not granted any rights under this section.<br/>
<br/>
20. Applicable Law and Venue<br/>
PLEASE READ THE FOLLOWING PARAGRAPH CAREFULLY BECAUSE IT REQUIRES YOU TO ARBITRATE DISPUTES WITH Cander AND LIMITS THE MANNER IN WHICH YOU CAN SEEK RELIEF FROM Cander.<br/>
You and Cander agree to arbitrate any dispute arising from these Terms of Service or your use of the Cander Service, except that you and Cander are not required to arbitrate any dispute in which either party solely seeks equitable relief for the alleged unlawful use of copyrights, trademarks, trade names, logos, trade secrets, or patents. ARBITRATION PREVENTS YOU FROM SUING IN COURT OR FROM HAVING A JURY TRIAL. You and Cander agree that you will notify each other in writing of any dispute within thirty (30) days of when it arises. Notice to Cander shall be sent to Cander, LLC, Attn: Legal Department, [ADDRESS]. You and Cander further agree: to attempt informal resolution prior to any demand for arbitration; that any arbitration will occur in Los Angeles County, California; that arbitration will be conducted confidentially by a single arbitrator in accordance with the rules of JAMS; and that the state or federal courts in Los Angeles County, California have exclusive jurisdiction over any appeals of an arbitration award and over any suit between the parties not subject to arbitration. Other than class procedures and remedies discussed below, the arbitrator has the authority to grant any remedy that would otherwise be available in court. Any dispute between the parties will be governed by this Agreement and the laws of the State of California and applicable United States law, without giving effect to any conflict of laws principles that may provide for the application of the law of another jurisdiction. Whether the dispute is heard in arbitration or in court, you and Cander will not commence against the other a class action, class arbitration or other representative action or proceeding.<br/>
<br/>
21. Miscellaneous.<br/>
21.1 Notice.<br/>
Cander may provide you with notices, including those regarding changes to Cander's terms and conditions, by email, regular mail or postings on the Cander Services. If given by email, notice will be deemed given twenty-four (24) hours after email is sent, unless Cander is notified that the email address is invalid. Alternatively, we may give you legal notice by mail to a postal address, if provided by you through the Cander Service. In such case, notice will be deemed given three days after the date of mailing. Notice posted on the Cander Service is deemed given ten (10) days following the initial posting or sooner in the event that we or you have received reasonably clear acknowledgment of such notice form you.<br/>
21.2 Waiver.<br/>
The failure of either you or us to exercise or enforce any right or provision of these Terms of Service will not constitute a waiver of such right or provision. Any waiver of any provision of these Terms of Service will be effective only if in writing and signed by the relevant party.<br/>
21.3 Severability.<br/>
If any provision of these Terms of Service or any guidelines is held to be unlawful, void, or for any reason unenforceable, then for both you and us that provision will be limited or eliminated from these Terms of Service to the minimum extent necessary and will not affect the validity and enforceability of any remaining provisions.<br/>
21.4 Assignment.<br/>
These Terms of Service and related Guidelines, and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by Cander without restriction. Any assignment attempted to be made in violation of this Terms of Service shall be void.<br/>
21.5 Survival.<br/>
Upon termination of these Terms of Service, any provision which, by its nature or express terms should survive, will survive such termination or expiration, including, but not limited to, Sections 7, 8, 11(b)(ii), 11(c), 11(d), 12, 1520.<br/>
21.6 Headings.<br/>
The heading references herein are for convenience purposes only, do not constitute a part of these Terms of Service, and will not be deemed to limit or affect any of the provisions of it.<br/>
21.7 Entire Agreement.<br/>
The Terms of Service, together with the Terms of Sale, the Privacy Policy and the Guidance, is the entire agreement between you and Cander relating to the subject matter herein and will not be modified except in writing, signed or otherwise agreed to by both parties, or by a change to these Terms of Service or Guidelines made by Cander as set forth in Section 6 above.<br/>
21.8 Claims.<br/>
If you are a consumer resident in the European Union and you disagree with the above, we encourage you contact us as soon as possible after you start using the Cander Service at legal@Cander.com since otherwise they will be binding on you after a reasonable time period (usually 30 days unless there are exceptional circumstances). The following section only applies to you if you are resident in the USA or elsewhere in the world (but does not apply if you are a consumer resident in the European Union): YOU AND Cander AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE Cander SERVICE MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.<br/>
21.9 Disclosures.<br/>
The Cander Service is offered by Cander, LLC, located at: [ADDRESS] and email: help@Cander.com. If you are a California resident, you may have this same information emailed to you by sending a letter to the foregoing address with your email address and a request for this information.<br/>
21.10 Requests for User Information<br/>
All requests for information or documents must be made using the appropriate level of legal process, and must be properly served on Cander via Cander's registered agent.<br/>
Please note that Cander does not accept requests for information or documents, or service of process, via email or fax and will not respond to such requests. All requests must include the information you may have that will help us identify the relevant records (e.g. the Cander username: <br/>
https://www.Cander.com /username), the specific information requested, and its relationship to your investigation.<br/>
Please also note that limiting your request to the relevant records (e.g. a limited time period) will facilitate efficient processing of your request.<br/>
<br/>
</div>

@endsection

@section('scripts')
    @parent

    <script type="text/javascript">
        var AppBridge = window['app-bridge'];
        var actions = AppBridge.actions;
        var TitleBar = actions.TitleBar;
        var Button = actions.Button;
        var Redirect = actions.Redirect;
        var titleBarOptions = {
            title: 'Terms',
        };
        var myTitleBar = TitleBar.create(app, titleBarOptions);
    </script>
@endsection
